### PR TITLE
Add .eslintignore file.

### PR DESCRIPTION
**Pull request by mattcollier**
@aljones15 I found that this works for being able to test files in folders of arbitrary depth in `lib` and `test` folder.

### CODE REVIEW

**Comment by aljones15** [comment]
we got a problem then this fails on my computer, but the other pattern does work also lib test will only work on the lib and test dirs and not the schemas one.

**Comment by mattcollier** [comment]
@aljones15 how does it fail for you?  Good call on the schemas folder, that's just a matter of adding schemas to the list of folder being checked.

**Comment by aljones15** [comment]
> @aljones15 how does it fail for you? Good call on the schemas folder, that's just a matter of adding schemas to the list of folder being checked.

no longer fails the .eslint ignore works. However I think my last comment got accross the issue:

eslint **/*.js

recursively checks all *.js files in the project. 
on the other hand this one does a simple dir based check.
what is the advantage of this? I saw @davidlehn linked to the glob stuff, but I did a test of the
eslint **/*.js

on a dir structure like this

/nested/nested/nested
with each dir having a js file in it with an error and it caught all the errors.

**Comment by aljones15** [comment]
went ahead and took this the additional .eslint ignore will help in any case we do need to watch in the future if new dirs are added though.

**Pull request merged**
